[package]
name = "example-grpc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tonic = "0.10"
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
tonic-build = "0.10"
