[workspace]
members = [".", "examples/*"]

[workspace.package]
authors = [
  "Mattia Penati <mattia.penati@protonmail.com>",
  "Sylwester Rąpała <sylwesterrapala@outlook.com>",
]
edition = "2021"
license = "Apache-2.0 OR MIT"

[workspace.dependencies]
axum = { version = "0.8", default-features = false }
opentelemetry = { version = "0.32", default-features = false }
opentelemetry-otlp = { version = "0.32", features = [
  "grpc-tonic",
  "metrics",
  "trace",
] }
opentelemetry_sdk = { version = "0.32", features = ["metrics", "rt-tokio"] }
reqwest = { version = "0.13", default-features = false }
tower-otel = { path = "." }
tracing = { version = "0.1", default-features = false }
tracing-opentelemetry = { version = "0.33", default-features = false }
tracing-subscriber = "0.3"

[package]
name = "tower-otel"
version = "0.10.0"
description = "OpenTelemetry layer for HTTP/gRPC services"
keywords = ["opentelemetry", "tracing", "tower", "http", "grpc"]
homepage = "https://github.com/mattiapenati/tower-otel"
repository = "https://github.com/mattiapenati/tower-otel"
documentation = "https://docs.rs/tower-otel"
edition.workspace = true
authors.workspace = true
license.workspace = true
autoexamples = false

[dependencies]
axum = { workspace = true, optional = true, default-features = false, features = [
  "matched-path",
  "tokio",
] }
cfg-if = "1"
http = "1"
http-body = "1"
opentelemetry = { workspace = true, default-features = false, features = [
  "metrics",
] }
pin-project = "1"
reqwest = { workspace = true, optional = true, default-features = false }
tower-layer = "0.3"
tower-service = "0.3"
tracing = { workspace = true, default-features = false }
tracing-opentelemetry = { workspace = true, default-features = false }

[features]
default = ["propagate"]
propagate = []
axum = ["dep:axum"]
reqwest_013 = ["dep:reqwest"]
