[package]
name = "tower-otel"
version = "0.1.0"
edition = "2021"
authors = ["Mattia Penati <mattia.penati@protonmail.com>"]

[dependencies]
pin-project-lite = "0.2.13"
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.40", default-features = false }
